### ISSUE TITLE
triple backticks from redcarpet to kramdown

### ISSUE THREAD

**Issue by outsinre** [planetjekyll/quickrefs#2]
Hi, I get to this repo while searching [fenced code block](https://talk.jekyllrb.com/t/backtik-with-kramdown/1949/9) issue in `kramdown`.

Previously I use `redcarpet`, fenced code in (nested) list is to indent _4 x level spaces_. But this does **NOT** work in _kramdown_.

Luckly, I found in this FAQ that code should _align with list item_ and _add empty lines before and after fence_. Save my world!

The question is I have too many markdown posts on Github pages. It would be tedious and impossible to update fenced code post by post.

Is there a better solution? Just wait for Github/Jekyll update?

**Comment by geraldb** [comment]
Please post questions to jekyll talk forum. Thanks. Cheers.
